const SUPABASE_URL="https://eznwdwrvzfpepqookuhs.supabase.co";
const SUPABASE_KEY="sb_publishable_yGM2eGpJztrS-34HblbaXg_iAF2-mCa";
const VAPID_PUBLIC_KEY="BKowPmpfVE1SK4wDVmvmdkm0bZPcwCDTww05_cFr5zmoTAZMZV1_-wg2UBqXBNMGYJqmsFDDAgL1VIOK7Bac9so";

const CATEGORIES={
"All":["Sweet & Romantic","Appreciation","Thinking of You","Encouragement","Make Her Smile","Thank Her","Goodnight","Flirty"],
"Sweet & Romantic":["I hope you know how deeply loved you are. ❤️","I'd choose you all over again.","You make ordinary days feel special just by being in them.","Just a reminder: you're my favorite person.","I still get happy knowing I get to call you mine."],
"Appreciation":["I notice everything you do, and I appreciate you more than I say.","Thank you for being the amazing woman you are.","You make our home and our life better in so many little ways.","I don't ever want you to wonder if I appreciate you. I do. So much.","I'm lucky to have you beside me."],
"Thinking of You":["Just thinking about you and smiling.","You popped into my head, so I had to tell you I love you.","Hope your day is going okay. I'm thinking about you.","Wish I could give you a hug right now.","Random reminder that you're on my mind."],
"Encouragement":["You've got this. I believe in you completely.","Whatever today throws at you, remember I'm in your corner.","You're stronger than you realize, and I'm proud of you.","Take a breath. You're doing better than you think.","I'm always cheering for you."],
"Make Her Smile":["Official announcement: you're still my favorite human.","I love you more than snacks. And you know that's serious.","If loving you were a job, I'd happily work overtime.","You are ridiculously cute. I don't make the rules.","Just checking in to remind you that you're stuck with me. ❤️"],
"Thank Her":["Thank you for loving me the way you do.","Thank you for all the little things I sometimes forget to say thank you for.","Thank you for being patient, kind, and you.","I don't say it enough: thank you for being in my life.","Thank you for making life feel like home."],
"Goodnight":["Goodnight, beautiful. I hope you sleep knowing how loved you are.","Sleep well, my love. Tomorrow is another day together.","Goodnight ❤️ I'm grateful I get to love you.","Rest up, beautiful. I'll be thinking about you.","Sweet dreams to my favorite person."],
"Flirty":["Just so we're clear, I still think you're incredibly hot.","I have a crush on you. It may be permanent.","You looked especially good today. Just saying.","I miss your face… and maybe a few other things. 😉","Still very much into you. Carry on."]
};
const DEFAULT={name:"",phone:"",remindersEnabled:true,reminderCount:3,times:["09:00","13:00","19:30"],avoidRepeats:true,customMessages:"",sent:[],used:[],deviceId:""};
let state={...DEFAULT,...load()},category="Sweet & Romantic",currentMessage="";

function load(){try{return JSON.parse(localStorage.getItem("dearlyState")||"{}")}catch{return {}}}
function save(){localStorage.setItem("dearlyState",JSON.stringify(state))}
function $(id){return document.getElementById(id)}
function toast(t){const e=$("toast");e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),1800)}
function formatTime(t){let[h,m]=t.split(":").map(Number),ap=h>=12?"PM":"AM";h=h%12||12;return `${h}:${String(m).padStart(2,"0")} ${ap}`}
function allMessages(){return Object.values(CATEGORIES).flat().concat((state.customMessages||"").split(/\n/).map(x=>x.trim()).filter(Boolean))}
function pickMessage(){let pool=category==="All"?allMessages():[...(CATEGORIES[category]||CATEGORIES["Sweet & Romantic"])];if(state.avoidRepeats){const fresh=pool.filter(x=>!(state.used||[]).includes(x));if(fresh.length)pool=fresh}currentMessage=pool[Math.floor(Math.random()*pool.length)]||"I love you. ❤️";state.used=[...(state.used||[]),currentMessage].slice(-20);save();renderMessage()}
function renderMessage(){$("message").textContent=currentMessage;$("categoryLabel").textContent=category}
function renderChips(){$("categoryChips").innerHTML=["All",...CATEGORIES.All].map(c=>`<button class="chip ${c===category?"active":""}" data-cat="${c}">${c}</button>`).join("");document.querySelectorAll(".chip").forEach(b=>b.onclick=()=>{category=b.dataset.cat;renderChips();pickMessage()})}
function renderStats(){const today=new Date().toISOString().slice(0,10),sent=(state.sent||[]),n=sent.filter(x=>x.date===today).length;$("sentToday").textContent=n;$("totalSent").textContent=sent.length;let streak=0,d=new Date();for(const date of [...new Set(sent.map(x=>x.date))].sort().reverse()){const ds=d.toISOString().slice(0,10);if(date===ds){streak++;d.setDate(d.getDate()-1)}else if(date<ds)break}$("streak").textContent=streak}
function renderReminderSummary(){const n=Number(state.reminderCount)||1;$("reminderSummary").textContent=`${n} reminder${n===1?"":"s"} a day`;$("reminderTimes").textContent=(state.times||[]).slice(0,n).map(formatTime).join(" · ")}
function render(){const has=!!state.name&&!!state.phone;$("setupView").classList.toggle("hidden",has);$("homeView").classList.toggle("hidden",!has);$("settingsView").classList.add("hidden");$("recipientName").textContent=state.name||"her";$("avatar").textContent=(state.name||"♡").charAt(0).toUpperCase();renderChips();renderStats();renderReminderSummary();if(!currentMessage)pickMessage()}
function openSettings(){$("homeView").classList.add("hidden");$("setupView").classList.add("hidden");$("settingsView").classList.remove("hidden");$("settingsName").value=state.name;$("settingsPhone").value=state.phone;$("remindersEnabled").checked=state.remindersEnabled;$("avoidRepeats").checked=state.avoidRepeats;$("reminderCount").innerHTML=Array.from({length:10},(_,i)=>`<option value="${i+1}">${i+1}</option>`).join("");$("reminderCount").value=state.reminderCount;$("customMessages").value=state.customMessages||"";renderTimeFields();updatePushStatus()}
function renderTimeFields(){const n=Number($("reminderCount").value||state.reminderCount||3);state.times=state.times||[];while(state.times.length<n)state.times.push("09:00");$("timeFields").innerHTML=Array.from({length:n},(_,i)=>`<label>Reminder ${i+1}<input class="time-input" data-i="${i}" type="time" value="${state.times[i]||"09:00"}"></label>`).join("")}
function saveSetup(){const name=$("setupName").value.trim(),phone=$("setupPhone").value.trim();if(!name||!phone)return toast("Please enter her name and phone number.");state.name=name;state.phone=phone;if(!state.deviceId)state.deviceId=crypto.randomUUID();save();render();toast("You're all set ❤️");}
function saveSettings(){state.name=$("settingsName").value.trim();state.phone=$("settingsPhone").value.trim();state.remindersEnabled=$("remindersEnabled").checked;state.reminderCount=Number($("reminderCount").value);state.times=[...document.querySelectorAll(".time-input")].map(x=>x.value||"09:00");state.avoidRepeats=$("avoidRepeats").checked;state.customMessages=$("customMessages").value;if(!state.deviceId)state.deviceId=crypto.randomUUID();save();render();toast("Settings saved.");}
function textHer(){if(!state.phone)return toast("Add her phone number in Settings.");state.sent.push({date:new Date().toISOString().slice(0,10),message:currentMessage,at:new Date().toISOString()});save();renderStats();window.location.href=`sms:${state.phone}?&body=${encodeURIComponent(currentMessage)}`;}
async function copyMessage(){try{await navigator.clipboard.writeText(currentMessage);toast("Message copied.")}catch{toast("Copy isn't available here.")}}
function urlBase64ToUint8Array(base64String){const padding="=".repeat((4-base64String.length%4)%4),base64=(base64String+padding).replace(/-/g,"+").replace(/_/g,"/"),raw=atob(base64);return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))}
async function registerPush(){if(!("serviceWorker" in navigator)||!("PushManager" in window)||!("Notification" in window))throw new Error("Push notifications are not supported by this browser.");if(!window.matchMedia("(display-mode: standalone)").matches && !navigator.standalone){toast("On iPhone, add Dearly to your Home Screen first.");return}const permission=await Notification.requestPermission();if(permission!=="granted"){toast("Notifications were not allowed.");return}const reg=await navigator.serviceWorker.ready;let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:urlBase64ToUint8Array(VAPID_PUBLIC_KEY)});if(!state.deviceId)state.deviceId=crypto.randomUUID();const payload={device_id:state.deviceId,wife_name:state.name,phone:state.phone,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||"America/Detroit",reminder_times:state.times.slice(0,state.reminderCount),reminders_enabled:state.remindersEnabled,push_subscription:sub.toJSON()};const r=await fetch(`${SUPABASE_URL}/rest/v1/dearly_devices?on_conflict=device_id`,{method:"POST",headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`, "Content-Type":"application/json",Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify(payload)});if(!r.ok)throw new Error("Could not save the push subscription ("+r.status+")");save();toast("Background notifications are enabled ❤️");updatePushStatus()}
async function updatePushStatus(){const e=$("pushStatus");if(!("Notification" in window)){e.textContent="This browser does not support notifications.";return}e.textContent=Notification.permission==="granted"?"Push permission is enabled on this iPhone.":"Push permission has not been granted yet."}
$("saveSetup").onclick=saveSetup;$("settingsBtn").onclick=openSettings;$("backBtn").onclick=render;$("editRecipient").onclick=openSettings;$("newMessage").onclick=pickMessage;$("textHer").onclick=textHer;$("copyMessage").onclick=copyMessage;$("saveSettings").onclick=saveSettings;$("notificationBtn").onclick=registerPush;$("requestNotifications").onclick=registerPush;$("reminderCount").onchange=renderTimeFields;
if("serviceWorker" in navigator)navigator.serviceWorker.register("./service-worker.js").catch(console.error);
render();updatePushStatus();