const SUPABASE_URL="https://eznwdwrvzfpepqookuhs.supabase.co";
const SUPABASE_KEY="sb_publishable_yGM2eGpJztrS-34HblbaXg_iAF2-mCa";
const VAPID_PUBLIC_KEY="BKU4bunUhkGcz5yUGNcORegKvXc7nSHW9A7ke0_HGCPNgxrbh4oqlbYtehNKOzi4iifJwtkX2_6UxGYbc0Z66Ks";

const CATEGORIES={
  "Sweet & Romantic": [
    "I love you. Just wanted you to know that.",
    "You make my life better just by being in it.",
    "I still get butterflies when I think about you.",
    "I'd choose you again in a heartbeat.",
    "You are my favorite part of every day.",
    "I love coming home to you.",
    "You're the person I want beside me for all of it.",
    "I hope you know how much you mean to me.",
    "I love the life we're building together.",
    "You make even ordinary days feel special.",
    "I really, really love you.",
    "You're my favorite person. Always.",
    "I'd rather do nothing with you than anything without you.",
    "I love your smile more than you know.",
    "You make my heart happy.",
    "I can't believe I get to call you mine.",
    "I love being your husband.",
    "You are still the one I want to tell everything to.",
    "I hope you never doubt how loved you are.",
    "You're my safe place.",
    "I love the little life we have together.",
    "I'd pick you in every lifetime.",
    "You make me want to be a better man.",
    "I love the way you make our house feel like home.",
    "You're the best thing that happened to me.",
    "I love you more than I probably say out loud.",
    "Just a reminder that you're my favorite.",
    "I love waking up knowing you're in my life.",
    "You have my whole heart.",
    "I'll never get tired of loving you.",
    "You're the person I want beside me when I'm old and gray.",
    "I love all the little things about you.",
    "You make me smile without even trying.",
    "I still have a huge crush on you.",
    "You're beautiful, inside and out.",
    "I love your laugh.",
    "I love the way you care about people.",
    "I love being on your team.",
    "You're my person.",
    "I don't say it enough, but I love you like crazy.",
    "I love every version of you.",
    "You're worth every good thing coming your way.",
    "I feel lucky that I get to do life with you.",
    "I love you on the easy days and the hard ones.",
    "You make my world feel a little softer.",
    "I wouldn't trade what we have for anything.",
    "You're home to me.",
    "I love having you in my corner.",
    "You are one of the best parts of my life.",
    "I hope today reminds you how special you are.",
    "I love you exactly as you are.",
    "I love that I can be completely myself with you.",
    "You make me feel incredibly lucky.",
    "I'd still want you if I had to start all over.",
    "I love the way we can laugh at the dumbest things.",
    "You're the first person I want to tell good news to.",
    "You're the person I want to celebrate with.",
    "I love your heart.",
    "I love how much love you give to the people around you.",
    "You make me proud to be your husband.",
    "I love every little memory we've made.",
    "I can't wait for all the memories we haven't made yet.",
    "You make forever sound pretty good.",
    "I love sitting next to you, even when we're doing absolutely nothing.",
    "I love our weird little life together.",
    "You make me feel understood.",
    "I love that you're you.",
    "You're my favorite hello and my hardest goodbye.",
    "I hope you know I'm always choosing you.",
    "I love you more today than yesterday.",
    "You're the best part of coming home.",
    "I love your face. Even when you're making that face.",
    "I'd rather have a boring Tuesday with you than an exciting day without you.",
    "You make my life feel fuller.",
    "I love how comfortable we are together.",
    "You are so easy to love.",
    "I'll never stop being grateful for you.",
    "I love the way you love me.",
    "You make me want to slow down and enjoy life.",
    "I love knowing we're in this together.",
    "You're still my favorite notification.",
    "I love being able to call you my wife.",
    "You make my heart feel full.",
    "I hope you feel loved today.",
    "I love you, plain and simple.",
    "You're the person I want to grow old with.",
    "I love our little moments more than the big ones.",
    "You make life better.",
    "I'd choose you over and over.",
    "I love you more than words can really explain.",
    "You're my favorite part of us.",
    "I love being married to you.",
    "You are incredibly special to me.",
    "I hope you never forget that I love you.",
    "I love you. That's the whole text.",
    "Just in case you needed a reminder: you're loved.",
    "I'd pick you every single time.",
    "I love you, beautiful.",
    "You're my forever person.",
    "Still crazy about you."
  ],
  "Appreciation": [
    "I noticed what you did today. Thank you.",
    "I really appreciate everything you do for us.",
    "Thank you for all the little things you do that nobody else sees.",
    "I don't say thank you enough.",
    "You do so much for our family.",
    "I appreciate you more than I probably show.",
    "Thank you for making our home feel like home.",
    "I see how hard you work.",
    "Thank you for always trying.",
    "I appreciate the way you take care of things.",
    "Thank you for being there when I need you.",
    "I notice how much you give to everyone else.",
    "You deserve to hear thank you more often.",
    "I appreciate having you in my life.",
    "Thank you for putting up with me.",
    "I know I don't always say it, but I notice.",
    "Thank you for everything you do for us.",
    "I appreciate how much thought you put into things.",
    "Thank you for making life easier in so many ways.",
    "I appreciate your patience with me.",
    "Thank you for being someone I can count on.",
    "I see the effort you put in.",
    "I appreciate your heart.",
    "Thank you for caring so much.",
    "I appreciate all the things you handle every day.",
    "Thank you for making me laugh.",
    "I appreciate how you always think about other people.",
    "Thank you for being you.",
    "I don't take you for granted.",
    "I appreciate you. A lot.",
    "Thank you for all the sacrifices you make.",
    "I appreciate how much love you put into our family.",
    "Thank you for listening to me.",
    "I appreciate the way you support me.",
    "Thank you for believing in me.",
    "I appreciate your honesty.",
    "Thank you for being patient when I'm not at my best.",
    "I see everything you do, even when I don't mention it.",
    "Thank you for making the hard days easier.",
    "I appreciate how dependable you are.",
    "Thank you for all the little acts of love.",
    "I appreciate the way you care about our future.",
    "Thank you for always making room for me.",
    "I appreciate your kindness.",
    "Thank you for being my teammate.",
    "I appreciate how much you do without asking for recognition.",
    "Thank you for making our life ours.",
    "I appreciate your sense of humor.",
    "Thank you for being someone I can trust.",
    "I notice when you go out of your way for me.",
    "I appreciate how much you care.",
    "Thank you for all the things you do behind the scenes.",
    "I appreciate the way you show love.",
    "Thank you for sticking with me through difficult days.",
    "I appreciate every effort you make.",
    "Thank you for being in my corner.",
    "I appreciate your strength.",
    "Thank you for making me feel supported.",
    "I appreciate how you keep going even when you're tired.",
    "Thank you for everything you bring into my life.",
    "I appreciate your patience, even when I don't deserve it.",
    "Thank you for being so thoughtful.",
    "I appreciate all the ways you make our life better.",
    "Thank you for the laughs.",
    "I appreciate how much you care about the people you love.",
    "Thank you for being my person.",
    "I appreciate your resilience.",
    "Thank you for making me feel at home.",
    "I appreciate your effort more than you know.",
    "Thank you for all the things you do that make me smile.",
    "I appreciate having you beside me.",
    "Thank you for loving me through my imperfections.",
    "I appreciate how you always try to understand me.",
    "Thank you for giving so much of yourself.",
    "I appreciate you every single day.",
    "Thank you for being someone I can lean on.",
    "I appreciate the way you make even small things feel important.",
    "Thank you for your patience and understanding.",
    "I appreciate how much you do for our family.",
    "Thank you for being the person you are.",
    "I appreciate every cup of coffee, every hug, and every little thing.",
    "Thank you for caring about the details.",
    "I appreciate how you make things feel manageable.",
    "Thank you for being my partner in all of this.",
    "I appreciate your loyalty.",
    "Thank you for choosing me.",
    "I appreciate how much love you put into our everyday life.",
    "Thank you for all the things you do that I sometimes overlook.",
    "I appreciate you more than I can fit into one text.",
    "Thank you for making me feel cared for.",
    "I appreciate how hard you work.",
    "Thank you for always giving your best.",
    "I appreciate you today and every day.",
    "Thank you for being one of the best things in my life.",
    "I see you, and I appreciate you.",
    "Thank you for everything. Seriously.",
    "You do more than you realize, and I appreciate it.",
    "Thank you for being my teammate, my support, and my favorite person.",
    "I really do notice all the little things you do.",
    "I appreciate having you beside me through all of this."
  ],
  "Thinking of You": [
    "Just thinking about you.",
    "You popped into my head, so I had to say hi.",
    "Hope your day is going okay.",
    "Just wanted you to know you're on my mind.",
    "I was thinking about you and smiling.",
    "Wish I could give you a hug right now.",
    "Random thought: I love you.",
    "Just checking in on my favorite person.",
    "I hope you're having a good day.",
    "Thinking about you over here.",
    "I miss you.",
    "Can't wait to see you later.",
    "You crossed my mind and made me smile.",
    "Hope you're taking care of yourself today.",
    "Just sending you a little love.",
    "I wish you were here with me.",
    "I was just thinking how lucky I am to have you.",
    "Hope something makes you smile today.",
    "You're on my mind.",
    "Just wanted to check in and say I love you.",
    "I hope work isn't being too crazy today.",
    "Sending you a hug from wherever I am.",
    "Can't wait to hear about your day.",
    "Thinking about that beautiful face of yours.",
    "I hope you're doing okay.",
    "Just a little reminder that I'm thinking about you.",
    "I wonder what you're doing right now.",
    "I miss hearing your voice.",
    "Wish I could steal a few minutes with you.",
    "Hope you're having one of those really good days.",
    "Thinking about our last laugh together.",
    "I can't wait to be home with you.",
    "Just wanted to put a smile on your phone.",
    "I hope you know I'm thinking about you even when I'm busy.",
    "You're my favorite distraction.",
    "Thinking about you makes my day better.",
    "Hope you're getting a chance to breathe today.",
    "I'd really like a hug from you right now.",
    "Just checking on my girl.",
    "You're somewhere in my thoughts as usual.",
    "I hope today is being kind to you.",
    "I miss your face.",
    "Wish I could teleport to you for five minutes.",
    "Thinking about you and everything I love about you.",
    "Just sending a quick I love you.",
    "I hope you feel loved today.",
    "Can't wait to see that smile.",
    "I've got you on my mind.",
    "You were the first person I thought about this morning.",
    "You're probably not surprised that I'm thinking about you again.",
    "Just wanted to say hi to my favorite person.",
    "Hope you're doing something that makes you happy.",
    "I wish I could be sitting next to you right now.",
    "Thinking about you from over here.",
    "Just checking in because I love you.",
    "I hope your day gets easier from here.",
    "You make it very easy to miss you.",
    "Thinking about our next date already.",
    "I hope you know you're never far from my thoughts.",
    "Just wanted to send a little love your way.",
    "Missing you a little extra today.",
    "I can't wait to tell you something later.",
    "Thinking about your laugh.",
    "Hope you're having a decent day so far.",
    "I love when random thoughts of you pop up.",
    "You've been on my mind all morning.",
    "I hope you're smiling right now.",
    "Just wanted to make sure you know I love you.",
    "I wish I could pause everything and hang out with you.",
    "Thinking about you makes everything feel a little better.",
    "I hope you get some time for yourself today.",
    "I miss having you next to me.",
    "Just sending you a virtual hug.",
    "I wonder if you know how often I think about you.",
    "Hope you're okay, beautiful.",
    "Thinking about you is becoming a full-time job.",
    "Just a reminder that someone loves you very much.",
    "I can't wait until we're together again.",
    "I hope something good happens to you today.",
    "You've been in my head all day.",
    "Just wanted to say I miss you.",
    "Thinking about you and smiling like an idiot.",
    "Hope you're having a good one.",
    "I'd rather be hanging out with you right now.",
    "You're on my mind again. Shocking, I know.",
    "Just sending you some love between everything else.",
    "I hope your day has at least one really good moment.",
    "Can't wait to hear your voice later.",
    "Thinking about you is my favorite habit.",
    "Hope you're doing okay over there.",
    "Wish I could give you a real hug instead of this text.",
    "Just wanted to remind you that I love you.",
    "I hope you know I'm rooting for you today.",
    "You're the thought I didn't mind getting distracted by.",
    "Just checking in because you're important to me.",
    "Thinking of you. That's it. That's the text.",
    "Just wanted to send you a little love.",
    "I've been thinking about you again.",
    "Hope you know I'm thinking about you.",
    "Wish I could sit next to you right now."
  ],
  "Encouragement": [
    "You've got this.",
    "I believe in you.",
    "You're stronger than you think.",
    "Take it one thing at a time.",
    "I'm in your corner.",
    "You don't have to have everything figured out today.",
    "Just breathe. You can handle this.",
    "I'm proud of you for keeping going.",
    "You can do hard things.",
    "I know today might be a lot, but you're not alone.",
    "Don't forget how capable you are.",
    "I'm cheering for you.",
    "You're doing better than you think.",
    "One step at a time.",
    "You've made it through hard days before.",
    "I believe in what you're capable of.",
    "Give yourself some grace today.",
    "You don't have to be perfect.",
    "I'm here if you need me.",
    "Keep going. I've got you.",
    "You're allowed to have a hard day.",
    "You're more capable than you give yourself credit for.",
    "Whatever happens today, we'll figure it out.",
    "Don't let one bad moment define the whole day.",
    "I'm proud of you.",
    "You can handle whatever comes next.",
    "Remember to give yourself a little credit.",
    "You're doing your best, and that matters.",
    "I know you can get through this.",
    "Keep your head up, beautiful.",
    "You don't have to do everything at once.",
    "Take a breath and reset.",
    "I've got your back.",
    "You're not doing this alone.",
    "I know you're tired, but you're doing an amazing job.",
    "You're allowed to take a break.",
    "I trust you to get through this.",
    "You are stronger than this moment.",
    "Don't forget how far you've come.",
    "I'm always on your team.",
    "You're capable of more than you realize.",
    "Just focus on the next step.",
    "I believe in you even when you don't believe in yourself.",
    "You've got someone cheering for you over here.",
    "You're doing enough.",
    "Be kind to yourself today.",
    "Today doesn't have to be perfect to be good.",
    "You're going to get through this.",
    "I know things feel heavy sometimes. I'm here.",
    "Don't give up on yourself.",
    "You've got this, one breath at a time.",
    "I know you can do this.",
    "Whatever you need, I'm here.",
    "You're allowed to feel overwhelmed and still keep going.",
    "I see how hard you're trying.",
    "You're making progress, even if it doesn't feel like it.",
    "Keep going. I'm proud of you.",
    "You're more resilient than you realize.",
    "I'll be cheering you on the whole way.",
    "You don't have to carry everything by yourself.",
    "You've got me in your corner.",
    "Remember that you're loved while you're figuring things out.",
    "I know today isn't easy. I'm here.",
    "You're doing something hard, and you're doing it.",
    "Give yourself permission to slow down.",
    "You've already overcome so much.",
    "I know you can handle the next thing.",
    "Don't forget to breathe.",
    "You're not behind. You're moving at your own pace.",
    "You're doing better than yesterday, and that's enough.",
    "I believe in you completely.",
    "Whatever today brings, we'll face it together.",
    "You can take this one moment at a time.",
    "You're allowed to be proud of yourself.",
    "I hope you give yourself the same grace you give everyone else.",
    "You are not your worst day.",
    "You don't have to prove anything to me.",
    "I'm proud of the person you are.",
    "You're allowed to rest and start again.",
    "Keep going, sweetheart.",
    "I know you're capable of this.",
    "You have more strength than you think.",
    "I'll be here when you need me.",
    "You're doing a good job.",
    "Don't forget that I believe in you.",
    "You can get through today.",
    "Your best is enough.",
    "I'm proud of every little step.",
    "You're not alone in this.",
    "I've got faith in you.",
    "Take the pressure off yourself for a minute.",
    "You've got this, and you've got me.",
    "Whatever happens, you are loved.",
    "I believe in you. Always.",
    "Keep going. You're worth it.",
    "You can do this, beautiful.",
    "I'm right here with you, even when I'm not there.",
    "I'm proud of you for taking it one step at a time.",
    "You don't have to figure everything out right now.",
    "I'm here beside you through whatever today brings."
  ],
  "Make Her Smile": [
    "Just a reminder that you're ridiculously cute.",
    "I love you more than snacks. That's serious.",
    "Breaking news: you're still my favorite person.",
    "You're stuck with me. Sorry, I don't make the rules.",
    "Just checking to make sure you're still adorable.",
    "I have officially decided you're my favorite human.",
    "You're pretty great. Don't let it go to your head.",
    "I'd share my fries with you. That's love.",
    "You are dangerously easy to love.",
    "I hope this text makes you smile.",
    "You're cute. That's the whole message.",
    "Just wanted to interrupt your day with a little love.",
    "You're my favorite notification.",
    "I still have a massive crush on you.",
    "You make being married to you pretty awesome.",
    "Official report: you're still hot.",
    "I love your face. Even the weird expressions.",
    "You're my favorite person to annoy.",
    "I'd pick you for my teammate in literally anything.",
    "You're lucky you're so cute.",
    "I love you even when you steal the blankets.",
    "You're basically my favorite problem.",
    "I hope you're smiling because I just sent you this.",
    "You make my heart do dumb things.",
    "You're the reason I randomly smile at my phone.",
    "I'd flirt with you even if we just met.",
    "You're still very much my type.",
    "You're cute enough to get away with almost anything.",
    "I'd give you the last cookie. Probably.",
    "You're my favorite weirdo.",
    "I love how easily you make me laugh.",
    "You make ordinary days way more fun.",
    "You're pretty much impossible not to love.",
    "Just wanted to remind you that you're a total babe.",
    "You're the best part of my notifications.",
    "I have a serious case of the loves-you.",
    "You make my life more fun.",
    "I'd choose you for every ridiculous adventure.",
    "You're adorable. I have evidence.",
    "I love your ridiculous little personality.",
    "You're my favorite person to do nothing with.",
    "I hope you know how cute you are.",
    "You've got me smiling over here like an idiot.",
    "You're my favorite distraction.",
    "You're pretty hard to resist.",
    "I love that you're just as weird as I am.",
    "You make me laugh way too easily.",
    "You're my forever crush.",
    "I'd still flirt with you in the grocery store.",
    "You're kind of a big deal to me.",
    "Just so you know, you're still ridiculously attractive.",
    "I love your laugh more than I should probably admit.",
    "You make my day better without even trying.",
    "You're the cutest person I know. Sorry, everyone else.",
    "I'd choose you over a nap. That's huge.",
    "You are my favorite excuse to smile.",
    "I love being the person who gets to love you.",
    "You're a pretty excellent wife, just saying.",
    "I hope you're prepared for me to keep loving you forever.",
    "You make my heart happy and my brain distracted.",
    "You're way too easy to miss.",
    "I love how much fun you are.",
    "You're the only person I'd willingly share dessert with.",
    "You're cute enough that I forgot what I was going to say.",
    "I'd marry you again.",
    "You're my favorite human-shaped source of chaos.",
    "You make me laugh when I don't even want to.",
    "You're pretty great for someone who steals my stuff.",
    "I love your silly side.",
    "You're still the first person I want to send dumb thoughts to.",
    "You're my favorite person, and that's not even close.",
    "You're cute. I don't make the rules.",
    "I'd choose your company over almost anything.",
    "You make my phone more interesting.",
    "You're the reason I check my phone with a smile.",
    "I love how much fun life is with you.",
    "You're a babe. Case closed.",
    "You're my favorite person to bother.",
    "I hope you smiled at this. Mission accomplished.",
    "You're too cute for your own good.",
    "I'd flirt with you all over again.",
    "You make me ridiculously happy.",
    "You're my favorite little distraction.",
    "You're pretty much my dream girl.",
    "I love your goofy side.",
    "You're still the one who makes my stomach do that little flip.",
    "I'd share my blanket with you. Maybe.",
    "You're my favorite person on the planet.",
    "You make me smile like a fool.",
    "You're way too lovable.",
    "I can't believe I get to call you mine.",
    "You're cute enough to make me forget I'm annoyed.",
    "I love being silly with you.",
    "You're my favorite reason to laugh.",
    "You're basically sunshine with better jokes.",
    "I hope that made you grin.",
    "You're adorable, and yes, I said it again.",
    "Still crushing on you. Obviously.",
    "You're my favorite person to send completely unnecessary texts to.",
    "You're my favorite person to send random texts to."
  ],
  "Thank Her": [
    "Thank you for loving me.",
    "Thank you for choosing me.",
    "Thank you for being my wife.",
    "Thank you for being there for me.",
    "Thank you for believing in me.",
    "Thank you for all the little things you do.",
    "Thank you for being patient with me.",
    "Thank you for listening when I need to talk.",
    "Thank you for making me laugh.",
    "Thank you for being my safe place.",
    "Thank you for sticking with me.",
    "Thank you for making our house feel like home.",
    "Thank you for all the ways you show me you care.",
    "Thank you for always being yourself.",
    "Thank you for being someone I can count on.",
    "Thank you for loving me on my good days and bad ones.",
    "Thank you for giving me your time.",
    "Thank you for the hugs.",
    "Thank you for all the laughs we've shared.",
    "Thank you for making life feel less heavy.",
    "Thank you for being my teammate.",
    "Thank you for caring about the little things.",
    "Thank you for being honest with me.",
    "Thank you for always trying.",
    "Thank you for being so thoughtful.",
    "Thank you for making me feel loved.",
    "Thank you for being part of my life.",
    "Thank you for all the memories.",
    "Thank you for making ordinary days better.",
    "Thank you for believing that I can do better.",
    "Thank you for giving me chances.",
    "Thank you for being patient when I'm difficult.",
    "Thank you for knowing when I need a hug.",
    "Thank you for making me smile.",
    "Thank you for being my person.",
    "Thank you for always having my back.",
    "Thank you for everything you do for our family.",
    "Thank you for making me feel at home with you.",
    "Thank you for the little surprises.",
    "Thank you for the quiet moments.",
    "Thank you for every laugh.",
    "Thank you for every hug.",
    "Thank you for every conversation.",
    "Thank you for being someone I can be myself around.",
    "Thank you for loving me exactly where I am.",
    "Thank you for encouraging me.",
    "Thank you for reminding me what matters.",
    "Thank you for making me want to be better.",
    "Thank you for all the effort you put into us.",
    "Thank you for caring so deeply.",
    "Thank you for being so understanding.",
    "Thank you for making me feel important.",
    "Thank you for being my biggest supporter.",
    "Thank you for giving so much of yourself.",
    "Thank you for all the ways you take care of us.",
    "Thank you for making me laugh when I need it most.",
    "Thank you for being there even when things aren't easy.",
    "Thank you for never making me feel alone.",
    "Thank you for being such a huge part of my happiness.",
    "Thank you for the way you love me.",
    "Thank you for every little act of kindness.",
    "Thank you for making our life ours.",
    "Thank you for being patient with my flaws.",
    "Thank you for believing in us.",
    "Thank you for making me feel lucky.",
    "Thank you for all the moments I don't say thank you for.",
    "Thank you for being so easy to love.",
    "Thank you for being my partner.",
    "Thank you for making me feel understood.",
    "Thank you for caring about how my day went.",
    "Thank you for asking how I'm doing.",
    "Thank you for remembering the little things.",
    "Thank you for making me feel seen.",
    "Thank you for giving me something to look forward to.",
    "Thank you for being the person I want beside me.",
    "Thank you for every time you've made me feel better.",
    "Thank you for being there when I needed you.",
    "Thank you for being you.",
    "Thank you for giving me your heart.",
    "Thank you for sharing your life with me.",
    "Thank you for making me feel loved in so many different ways.",
    "Thank you for all the things you do without being asked.",
    "Thank you for being my favorite person.",
    "Thank you for making me feel like we're a team.",
    "Thank you for being someone I can trust.",
    "Thank you for your kindness.",
    "Thank you for your patience.",
    "Thank you for your sense of humor.",
    "Thank you for your strength.",
    "Thank you for your love.",
    "Thank you for every good memory.",
    "Thank you for every second we get together.",
    "Thank you for being part of my story.",
    "Thank you for letting me be part of yours.",
    "Thank you for choosing us.",
    "Thank you for making my life better.",
    "Thank you for everything, even the things I forget to mention.",
    "Thank you for being the woman I get to love.",
    "Thank you for all the love you put into our life.",
    "Thank you for making me feel like I belong."
  ],
  "Goodnight": [
    "Goodnight, beautiful. I love you.",
    "Sleep well, my love.",
    "Goodnight ❤️ I hope you sleep peacefully.",
    "Sweet dreams, beautiful.",
    "Goodnight to my favorite person.",
    "I hope you get some really good sleep tonight.",
    "Sleep tight. I love you.",
    "Goodnight, babe. See you in my dreams.",
    "Rest up, beautiful.",
    "I hope you fall asleep feeling loved.",
    "Goodnight. I'm grateful for you.",
    "Sleep well, my love. Tomorrow is another day together.",
    "Goodnight ❤️ I'm lucky I get to love you.",
    "Sweet dreams, gorgeous.",
    "Hope you sleep like a rock tonight.",
    "Goodnight, my favorite human.",
    "Get some rest, beautiful.",
    "I love you. Goodnight.",
    "Sleep well and don't let the blankets betray you.",
    "Goodnight, babe. I can't wait to see you tomorrow.",
    "I hope your dreams are as sweet as you are.",
    "Rest your pretty head.",
    "Goodnight to the woman who has my heart.",
    "Sleep well. You deserve the rest.",
    "Goodnight, love. I'm thinking about you.",
    "Sweet dreams, my favorite person.",
    "Hope tomorrow is a good one for you.",
    "Goodnight. I'm sending you a big hug.",
    "Sleep tight, beautiful.",
    "I hope you wake up feeling refreshed.",
    "Goodnight, sweetheart.",
    "Rest up. I love you more than you know.",
    "Goodnight ❤️ You are so loved.",
    "Sleep well, babe.",
    "Hope you get all the rest you need tonight.",
    "Goodnight, my love. I'm so glad I have you.",
    "Sweet dreams. I'll be thinking about you.",
    "Time to let that beautiful brain rest.",
    "Goodnight, gorgeous. I love your face.",
    "Sleep well, my girl.",
    "Goodnight. Thank you for being you.",
    "I hope tonight is peaceful for you.",
    "Rest easy, love.",
    "Goodnight to my favorite person in the world.",
    "Sleep well. Tomorrow needs that beautiful smile.",
    "Sweet dreams, babe.",
    "Goodnight. I can't wait to wake up next to you.",
    "Hope you sleep deeply tonight.",
    "Goodnight, beautiful. You made my day better.",
    "Rest up, sweetheart.",
    "I hope you end today knowing how loved you are.",
    "Goodnight. I'm lucky you're mine.",
    "Sleep well, my favorite human.",
    "Sweet dreams, love.",
    "Goodnight ❤️ I wish I could hug you right now.",
    "Get some sleep, beautiful.",
    "Goodnight, babe. Dream something fun.",
    "Rest your head and let the day go.",
    "Sleep well. I've got you.",
    "Goodnight, love. You deserve a peaceful night.",
    "Sweet dreams to my favorite girl.",
    "Goodnight. I love doing life with you.",
    "Hope your pillow is extra comfortable tonight.",
    "Sleep well, beautiful. See you tomorrow.",
    "Goodnight. One more reminder that I love you.",
    "Rest up, my love.",
    "Sweet dreams. You're my favorite thought before bed.",
    "Goodnight, sweetheart. I'm thinking of you.",
    "I hope you sleep as peacefully as you deserve.",
    "Goodnight, beautiful. I'm so thankful for you.",
    "Sleep tight, babe.",
    "Goodnight. I hope tomorrow is gentle with you.",
    "Rest well, love.",
    "Sweet dreams, gorgeous.",
    "Goodnight ❤️ You're the last person on my mind tonight.",
    "Sleep well, my favorite person.",
    "Goodnight. I love you more than I can say.",
    "Hope you get the best sleep tonight.",
    "Rest easy, beautiful.",
    "Goodnight, babe. I'm sending you all my love.",
    "Sweet dreams, my love.",
    "I hope you wake up knowing you're loved.",
    "Goodnight. I'm so glad I get to do life with you.",
    "Sleep well, sweetheart.",
    "Goodnight to my favorite face.",
    "Rest up. Tomorrow is waiting.",
    "Sweet dreams, beautiful.",
    "Goodnight. I hope you feel safe, loved, and peaceful.",
    "Sleep tight, my love.",
    "Goodnight ❤️ Thank you for today.",
    "Rest well, babe.",
    "I love you. Now go get some sleep.",
    "Goodnight, beautiful. You deserve a good night.",
    "Sweet dreams to the woman I love.",
    "Sleep well. I'll be thinking about you.",
    "Goodnight, my person.",
    "Rest up, love. You've earned it.",
    "Goodnight. I can't wait for tomorrow with you.",
    "Sweet dreams, babe.",
    "Sleep peacefully, beautiful."
  ],
  "Flirty": [
    "Just so we're clear, I still think you're incredibly hot.",
    "I still have a huge crush on you.",
    "You looked really good today.",
    "You're seriously attractive, you know that?",
    "I'd flirt with you even if we just met.",
    "I still get butterflies around you.",
    "You're making it very hard to concentrate over here.",
    "I miss your face. And maybe a few other things. 😉",
    "You're my favorite distraction.",
    "I'd definitely ask you out again.",
    "You're still very much my type.",
    "You look good in basically everything.",
    "I don't know how you keep getting prettier.",
    "Just wanted to remind you that you're hot.",
    "I have a crush on my wife. Seems unfair.",
    "You're dangerously attractive.",
    "I still get excited when I see you.",
    "You make it really hard to behave.",
    "You're pretty irresistible.",
    "I'd choose you for date night every time.",
    "I think you owe me a kiss.",
    "Just saying, you look amazing.",
    "You're my favorite person to flirt with.",
    "I still love looking at you.",
    "You're way too cute.",
    "I can't decide if I want to hug you or kiss you first.",
    "You make my heart race.",
    "I definitely married up.",
    "You're the kind of beautiful I never get tired of.",
    "Just a reminder that you're my girl.",
    "I still get a little nervous when you look at me like that.",
    "You have no business being that attractive.",
    "I'd cancel plans just to hang out with you.",
    "You're pretty much impossible to resist.",
    "I love when you get all dressed up.",
    "You make being married to you very fun.",
    "I'd pick you for a date even if I had to impress you all over again.",
    "You're still my favorite view.",
    "I have a serious weakness for you.",
    "You make me want to drop everything and come see you.",
    "I can't stop thinking about you.",
    "You're looking dangerously good lately.",
    "I'd flirt with you all night.",
    "You're still the one who gives me butterflies.",
    "I love when you catch me staring.",
    "You're way too easy on the eyes.",
    "I think you're ridiculously attractive.",
    "You make me forget what I was saying.",
    "I'd choose your lips over almost anything.",
    "You're my favorite temptation.",
    "I still want to take you on dates.",
    "You've got me completely distracted.",
    "I love seeing you smile at me.",
    "You're gorgeous. Just thought you should know.",
    "I'd happily spend the rest of my life flirting with you.",
    "You're my favorite kind of trouble.",
    "I still get that stupid grin when you walk into a room.",
    "You're absolutely my type.",
    "You make it hard to keep my hands to myself.",
    "I'd pick you again without hesitation.",
    "You're dangerously cute when you know you're being cute.",
    "I love when you look at me like that.",
    "You're still a total babe.",
    "I'd rather be kissing you right now.",
    "You're the only person who can distract me this easily.",
    "I think you owe me some quality time.",
    "You make me feel like a teenager with a crush.",
    "You're ridiculously easy to want.",
    "I love being attracted to you this much.",
    "You've still got it. Then again, you never lost it.",
    "You're my favorite person to get close to.",
    "I'd happily get lost with you.",
    "You're the reason date night is my favorite night.",
    "I still think you're sexy as hell.",
    "I'd choose you for another hundred dates.",
    "You're way too good at making me smile.",
    "I can't believe you're my wife and I still get to flirt with you.",
    "You're the best-looking person I know.",
    "I've got a serious case of the can't-stop-looking-at-you.",
    "You make me want to be closer to you.",
    "You're my favorite kind of distraction.",
    "I'd like to steal a kiss later.",
    "You still make my stomach do that little flip.",
    "I love how good you look when you're just being yourself.",
    "You're beautiful enough to stop me mid-sentence.",
    "I'd flirt with you anywhere.",
    "You're my forever crush.",
    "I still want to impress you.",
    "You're pretty much everything I find attractive.",
    "I love when you catch me checking you out.",
    "You make ordinary moments feel a little spicy.",
    "I'd rather be next to you right now.",
    "You're incredibly easy to want and even easier to love.",
    "I hope you know how attractive you are.",
    "You're still the woman I can't keep my eyes off.",
    "Just thinking about you has me smiling.",
    "I love you, and yes, I still think you're hot.",
    "You're my favorite person to have a crush on.",
    "You're still the woman I can't stop checking out.",
    "I definitely still have a thing for you."
  ]
};
const DEFAULT={name:"",phone:"",remindersEnabled:true,reminderCount:3,times:["09:00","13:00","19:30"],avoidRepeats:true,customMessages:"",sent:[],used:[],deviceId:""};
let state={...DEFAULT,...load()},category="Sweet & Romantic",currentMessage="";

function load(){try{return JSON.parse(localStorage.getItem("dearlyState")||"{}")}catch{return {}}}
function save(){localStorage.setItem("dearlyState",JSON.stringify(state))}
function $(id){return document.getElementById(id)}
function toast(t){const e=$("toast");e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),1800)}
function formatTime(t){let[h,m]=t.split(":").map(Number),ap=h>=12?"PM":"AM";h=h%12||12;return `${h}:${String(m).padStart(2,"0")} ${ap}`}
function allMessages(){return Object.entries(CATEGORIES).filter(([k])=>k!=="All").flatMap(([,v])=>v).concat((state.customMessages||"").split(/\n/).map(x=>x.trim()).filter(Boolean))}
function pickMessage(){let pool=category==="All"?allMessages():[...(CATEGORIES[category]||CATEGORIES["Sweet & Romantic"])];if(state.avoidRepeats){const fresh=pool.filter(x=>!(state.used||[]).includes(x));if(fresh.length)pool=fresh}currentMessage=pool[Math.floor(Math.random()*pool.length)]||"I love you. ❤️";state.used=[...(state.used||[]),currentMessage].slice(-100);save();renderMessage()}
function renderMessage(){$("message").textContent=currentMessage;$("categoryLabel").textContent=category}
function renderChips(){$("categoryChips").innerHTML=["All",...CATEGORIES.All].map(c=>`<button class="chip ${c===category?"active":""}" data-cat="${c}">${c}</button>`).join("");document.querySelectorAll(".chip").forEach(b=>b.onclick=()=>{category=b.dataset.cat;renderChips();pickMessage()})}
function renderStats(){const today=new Date().toISOString().slice(0,10),sent=(state.sent||[]),n=sent.filter(x=>x.date===today).length;$("sentToday").textContent=n;$("totalSent").textContent=sent.length;let streak=0,d=new Date();for(const date of [...new Set(sent.map(x=>x.date))].sort().reverse()){const ds=d.toISOString().slice(0,10);if(date===ds){streak++;d.setDate(d.getDate()-1)}else if(date<ds)break}$("streak").textContent=streak}
function renderReminderSummary(){const n=Number(state.reminderCount)||1;$("reminderSummary").textContent=`${n} reminder${n===1?"":"s"} a day`;$("reminderTimes").textContent=(state.times||[]).slice(0,n).map(formatTime).join(" · ")}
function render(){const has=!!state.name&&!!state.phone;$("setupView").classList.toggle("hidden",has);$("homeView").classList.toggle("hidden",!has);$("settingsView").classList.add("hidden");$("recipientName").textContent=state.name||"her";$("avatar").textContent=(state.name||"♡").charAt(0).toUpperCase();renderChips();renderStats();renderReminderSummary();if(!currentMessage)pickMessage()}
function openSettings(){$("homeView").classList.add("hidden");$("setupView").classList.add("hidden");$("settingsView").classList.remove("hidden");$("settingsName").value=state.name;$("settingsPhone").value=state.phone;$("remindersEnabled").checked=state.remindersEnabled;$("avoidRepeats").checked=state.avoidRepeats;$("reminderCount").innerHTML=Array.from({length:10},(_,i)=>`<option value="${i+1}">${i+1}</option>`).join("");$("reminderCount").value=state.reminderCount;$("customMessages").value=state.customMessages||"";renderTimeFields();updatePushStatus()}
function renderTimeFields(){const n=Number($("reminderCount").value||state.reminderCount||3);state.times=state.times||[];while(state.times.length<n)state.times.push("09:00");$("timeFields").innerHTML=Array.from({length:n},(_,i)=>`<label>Reminder ${i+1}<input class="time-input" data-i="${i}" type="time" value="${state.times[i]||"09:00"}"></label>`).join("")}
function saveSetup(){const name=$("setupName").value.trim(),phone=$("setupPhone").value.trim();if(!name||!phone)return toast("Please enter her name and phone number.");state.name=name;state.phone=phone;if(!state.deviceId)state.deviceId=crypto.randomUUID();save();render();toast("You're all set ❤️");}
function saveSettings(){state.name=$("settingsName").value.trim();state.phone=$("settingsPhone").value.trim();state.remindersEnabled=$("remindersEnabled").checked;state.reminderCount=Number($("reminderCount").value);state.times=[...document.querySelectorAll(".time-input")].map(x=>x.value||"09:00");state.avoidRepeats=$("avoidRepeats").checked;state.customMessages=$("customMessages").value;if(!state.deviceId)state.deviceId=crypto.randomUUID();save();render();toast("Settings saved.");}
function textHer(){if(!state.phone)return toast("Add her phone number in Settings.");state.sent.push({date:new Date().toISOString().slice(0,10),message:currentMessage,at:new Date().toISOString()});save();renderStats();window.location.href=`sms:${state.phone}?&body=${encodeURIComponent(currentMessage)}`;}
async function copyMessage(){try{await navigator.clipboard.writeText(currentMessage);toast("Message copied.")}catch{toast("Copy isn't available here.")}}
function urlBase64ToUint8Array(base64String){const padding="=".repeat((4-base64String.length%4)%4),base64=(base64String+padding).replace(/-/g,"+").replace(/_/g,"/"),raw=atob(base64);return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))}
async function registerPush(){if(!("serviceWorker" in navigator)||!("PushManager" in window)||!("Notification" in window))throw new Error("Push notifications are not supported by this browser.");if(!window.matchMedia("(display-mode: standalone)").matches&&!navigator.standalone){toast("On iPhone, add Dearly to your Home Screen first.");return}const permission=await Notification.requestPermission();if(permission!=="granted"){toast("Notifications were not allowed.");return}const reg=await navigator.serviceWorker.ready;let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:urlBase64ToUint8Array(VAPID_PUBLIC_KEY)});if(!state.deviceId)state.deviceId=crypto.randomUUID();const payload={device_id:state.deviceId,wife_name:state.name,phone:state.phone,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||"America/Detroit",reminder_times:state.times.slice(0,state.reminderCount),reminders_enabled:state.remindersEnabled,push_subscription:sub.toJSON()};const r=await fetch(`${SUPABASE_URL}/rest/v1/dearly_devices?on_conflict=device_id`,{method:"POST",headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,"Content-Type":"application/json",Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify(payload)});if(!r.ok)throw new Error("Could not save the push subscription ("+r.status+")");save();toast("Background notifications are enabled ❤️");updatePushStatus()}
async function updatePushStatus(){const e=$("pushStatus");if(!("Notification" in window)){e.textContent="This browser does not support notifications.";return}e.textContent=Notification.permission==="granted"?"Push permission is enabled on this iPhone.":"Push permission has not been granted yet."}
$("saveSetup").onclick=saveSetup;$("settingsBtn").onclick=openSettings;$("backBtn").onclick=render;$("editRecipient").onclick=openSettings;$("newMessage").onclick=pickMessage;$("textHer").onclick=textHer;$("copyMessage").onclick=copyMessage;$("saveSettings").onclick=saveSettings;$("notificationBtn").onclick=registerPush;$("requestNotifications").onclick=registerPush;$("reminderCount").onchange=renderTimeFields;
if("serviceWorker" in navigator)navigator.serviceWorker.register("./service-worker.js").catch(console.error);
render();updatePushStatus();
